### ISSUE TITLE
Turret re arm cost is not affected by story teller settings.

### ISSUE THREAD

**Issue by emelrad12** [Epicguru/AntimatterAnnihilation#9]
Set storyteller setting to for example 1% and it still shows the same cost for thunder gun.(haven't tested railgun yet)

**Comment by Epicguru** [comment]
This is intentional, see `ThunderGun.xml`:
`<factorByDifficulty>false</factorByDifficulty>`

Note that as of the latest Rimworld update, this is also how vanilla turrets work. From the patch notes:
_"Turret ammo cost is no longer factored by difficulty."_

I have always liked it this way more, and it seems that Tynan has also decided it's for the best. You can however always edit the XML to change this if you like.
